theme = "cino"
languageCode = "en-us"
baseurl = "https://cino.io/"
title = "Cino"
enableRobotsTXT = true

[services]
  [services.googleAnalytics]
    id = 'G-GCGJ9S1XSX'

[pagination]
  pagerSize = 10

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe= true

menu = ['main']
