theme = "cino"
languageCode = "en-us"
baseurl = "https://cino.io/"
title = "Cino"
enableRobotsTXT = true

[outputs]
  home = ['html', 'rss']

[services]
  [services.googleAnalytics]
    id = 'G-GCGJ9S1XSX'

[pagination]
  pagerSize = 10

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"

[taxonomies]
  category = "categories"
  tag = "tags"

menu = ['main']

[markup.goldmark.renderer]
  unsafe= true
